// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaeqs3L7AWNvlvFT0U1GcP4IVHOIB_7HI',
    appId: '1:222858399478:web:4d47c39dcc3f609e3d26d7',
    messagingSenderId: '222858399478',
    projectId: 'stuntapp-cd51d',
    authDomain: 'stuntapp-cd51d.firebaseapp.com',
    storageBucket: 'stuntapp-cd51d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzZ5gbdlkWjBMmsQalhhre8Q2Uud2vFqU',
    appId: '1:222858399478:android:3af3d6db5bb636313d26d7',
    messagingSenderId: '222858399478',
    projectId: 'stuntapp-cd51d',
    storageBucket: 'stuntapp-cd51d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0beboyDDhrnSlstX1bLb8ewF79tsTQWw',
    appId: '1:222858399478:ios:975ed0a14f0afd323d26d7',
    messagingSenderId: '222858399478',
    projectId: 'stuntapp-cd51d',
    storageBucket: 'stuntapp-cd51d.appspot.com',
    iosBundleId: 'com.example.stuntApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0beboyDDhrnSlstX1bLb8ewF79tsTQWw',
    appId: '1:222858399478:ios:8aec7cb27afd67073d26d7',
    messagingSenderId: '222858399478',
    projectId: 'stuntapp-cd51d',
    storageBucket: 'stuntapp-cd51d.appspot.com',
    iosBundleId: 'com.example.stuntApplication.RunnerTests',
  );
}
